### ISSUE TITLE
Création des pages

### ISSUE THREAD

**Issue by Landris18** [iTeam-S/iteam-s.github.io#1]
On doit coder 4pages, accueil, projets, qui sommes nous, nous rejoindre.

Je vous propose de travailler par groupe de deux personnes,

Page d'accueil : @Charla19  @arielle-i15 

Page projets + page qui sommes nous: @Jayah001 @hasintso2071 

Page nous rejoindre :@Xavier-001 @Smith-jpg 

On commence demain, les maquettes sont déjà prêtes.
Je compte sur vous.

Deadline 17 December 2020

**Comment by Charla19** [comment]
Bien reçu ;-)
Compte sur nous.

**Comment by gaetan1903** [comment]
@Landris18  Mettre les pages dans  un système de check List, on pourra suivre les évolutions après

- [ ] Acceuil

- [ ] Projets

- [ ] Qui sommes nous 

....

**Comment by Landris18** [comment]
@gaetan1903, tu l'as déjà fait

**Comment by gaetan1903** [comment]
sur la publication pour que ça s'affiche comme étant un état d'avancement @Landris18

**Comment by gaetan1903** [comment]
Je relance cet issue, je ne sais pas qui prend en charge la page projet actuellement?
quelqu'un peut me rafraîchir la mémoire...

**Comment by Landris18** [comment]
Toutes les pages sont terminées. 
Merci à vous tous.
32f0197
