### ISSUE TITLE
Demande de renfort

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/iteam-s.github.io#3]
Nous allons re-organiser les tâches ici... 

@Charla19  Tu fait appel à @naziradidier equipe back pour le boulot.. 

@Jayah001 tu vas prendre @c3k4ah  pour t'aider ... 

Merci

**Comment by Jayah001** [comment]
bien reçu @gaetan1903

**Comment by gaetan1903** [comment]
Changement de programme , 

On laisse tomber @naziradidier.

**Comment by gaetan1903** [comment]
Vous allez travailler solo, 

@Jayah001 & @Charla19 

Page Projets pour Charla , et  Page Qui sommes nous pour @Jayah001... 

Pages Nous rejoindre pour @c3k4ah

**Comment by Landris18** [comment]
Et @tonny-herison  ?

**Comment by gaetan1903** [comment]
@Landris18  

On laisse pour le secours, au plan B

**Comment by Landris18** [comment]
OK, @gaetan1903
